"""Pydantic schemas for MCQ generation module."""

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Core generated MCQ structures
# ---------------------------------------------------------------------------


class GeneratedOption(BaseModel):
    """Single answer option for a generated MCQ."""

    label: str = Field(..., min_length=1, max_length=5)
    text: str


class GeneratedQuestion(BaseModel):
    """
    MCQ generated by rule-based logic or LLM.

    `id` is optional and can be used later if you want to map
    generated questions back to database records.
    """

    id: int | None = None
    stem: str
    options: List[GeneratedOption]
    correct_label: str = Field(..., min_length=1, max_length=5)


# ---------------------------------------------------------------------------
# Request / Response payloads for the /mcq/generate endpoint
# ---------------------------------------------------------------------------


class MCQGenerateRequest(BaseModel):
    """
    Request to generate MCQs for a lecture.

    Either `lecture_text` or `lecture_id` must be provided.

    - If `lecture_text` is provided, the backend will generate questions
      directly from this text (no database lookup needed).
    - If `lecture_text` is None, the backend will resolve text from the DB
      using `lecture_id` and optional `section_id`.
    """

    lecture_text: Optional[str] = None
    lecture_id: Optional[int] = None
    section_id: Optional[int] = None
    num_questions: int = Field(default=3, ge=1, le=20)
    use_llm: bool = True


class MCQGenerateResponse(BaseModel):
    """
    Response containing generated MCQs.

    - `questions`: MCQs produced by rule-based logic / LLM
    - `question_ids`: IDs of the persisted Question rows in the DB, if saved
      (can be None if you only generate in-memory questions)
    """

    questions: List[GeneratedQuestion]
    question_ids: Optional[List[int]] = None
